---
- name: Disallow SSH password authentication via template
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/disablePasswordAuth.conf"
    dest: /etc/ssh/sshd_config.d/disablePasswordAuth.conf
    mode: "0644"
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - Restart sshd
