---
- name: Ensure apt is up to date on Ubuntu or Debian
  when: ansible_facts["os_family"] | lower in ["debian", "ubuntu"]
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
    autoremove: true

- name: Ensure dnf is up to date on RedHat
  when: ansible_facts["os_family"] | lower == "redhat"
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    autoremove: true
