---
# Restart ssh/sshd service, required by tasks/disable-password-auth.yml
- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: "{{ 'sshd' if ansible_facts['os_family'] | lower == 'redhat' else 'ssh' }}"
    state: restarted

- name: Reboot system
  become: true
  ansible.builtin.reboot:
  changed_when: false