---
# Restart ssh/sshd service, required by tasks/disable-password-auth.yml
- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: "{{ 'sshd' if ansible_facts['os_family'] | lower == 'redhat' else 'ssh' }}"
    state: restarted

- name: Enable ufw
  become: true
  community.general.ufw:
    state: enabled
    rule: deny
    logging: "on"

- name: Disable ufw
  become: true
  community.general.ufw:
    state: disabled
