---
- name: Display Boot Config
  ansible.builtin.debug:
    msg: >-
      Boot Configurations for roles {{ ansible_role_names }}:
      raspberry_pi_common_enable_i2c: {{ raspberry_pi_common_enable_i2c }},
      raspberry_pi_common_enable_spi: {{ raspberry_pi_common_enable_spi }},
      raspberry_pi_common_enable_uart: {{ raspberry_pi_common_enable_uart }},
      raspberry_pi_common_enable_watchdog: {{ raspberry_pi_common_enable_watchdog }},
      raspberry_pi_common_watchdog_max_temp: {{ raspberry_pi_common_watchdog_max_temp }}
      raspberry_pi_5_enable_pcie_without_hat: {{ raspberry_pi_5_enable_pcie_without_hat }},
      raspberry_pi_5_enable_pcie_gen3: {{ raspberry_pi_5_enable_pcie_gen3 }},
      raspberry_pi_5_has_rtc_batt: {{ raspberry_pi_5_has_rtc_batt }},
      raspberry_pi_5_usb_max_current_enable: {{ raspberry_pi_5_usb_max_current_enable }}

- name: Set /boot/firmware/config.txt using template
  become: true
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config_rpi5.txt.j2"
    dest: /boot/firmware/config.txt
    mode: "0644"
    # backup: true
