---
- name: Check if System is Supported
  ansible.builtin.fail:
    msg: This role is only supported on {{ raspberry_pi_common_supported_os }} systems
  when: ansible_facts["os_family"] | lower not in raspberry_pi_common_supported_os

# This needs to be run after setting boot config because the watchdog depends on hardware
- name: Set Watchdog
  ansible.builtin.import_tasks: watchdog.yml
